### ISSUE TITLE
Commits since client release/prod push

### ISSUE THREAD

**Issue by RedFlames** [RedFlames/CelesteNet#1]
The last Client release is dated **2022-01-22** on Gamebanana et al?

Latest Server update was after the commits on **2022-02-19** afaict

Server:
https://github.com/0x0ade/CelesteNet/compare/e8e9091cef0e0a6edf67476d23daf584da5725a9...main

Client:
https://github.com/0x0ade/CelesteNet/compare/d5be4412e9c15508451f4f8ea737e3ce035b375a...main

----

**Open PRs** to be potentially merged:
- Features:
   - ~~https://github.com/0x0ade/CelesteNet/pull/33~~
      <sub> - ~~opened 2022-08-21~~</sub> -- x <sub>(server-side changes only)</sub>
   - https://github.com/0x0ade/CelesteNet/pull/46
      <sub> - opened 2022-10-09</sub> -- :heart_decoration: <sub>(server-side changes only)</sub>
    - https://github.com/0x0ade/CelesteNet/pull/26
      <sub> - opened 2022-02-06</sub> -- :diamond_shape_with_a_dot_inside: <sub>(would become client-side changes only after #<sub></sub>46)</sub>
- Fixes:
    - https://github.com/0x0ade/CelesteNet/pull/29
      <sub> - opened 2022-05-24</sub> -- :diamond_shape_with_a_dot_inside: <sub>(client-side changes only)</sub>

----

**Closed PRs** that have been merged since:
- Features:
   - https://github.com/0x0ade/CelesteNet/pull/22 
     <sub> - merged on 2022-02-14 -- (client-side changes only)</sub>

   - https://github.com/0x0ade/CelesteNet/pull/27
     <sub> - merged on 2022-04-10</sub>
- Fixes:
    - https://github.com/0x0ade/CelesteNet/pull/23 
      <sub> - merged on 2022-01-22 -- (client-side changes only)</sub>

    - https://github.com/0x0ade/CelesteNet/pull/24 
      <sub> - merged on 2022-01-29 -- (client-side changes only)</sub>

    - _https://github.com/0x0ade/CelesteNet/pull/25_
       _<sub> - merged on 2022-02-14 -- </sub>// is actually live, but janky?..._

    - https://github.com/0x0ade/CelesteNet/pull/28
      <sub> - opened 2022-04-18</sub> -- :diamond_shape_with_a_dot_inside: <sub>(client-side changes only)</sub>

    - https://github.com/0x0ade/CelesteNet/pull/30
      <sub> - opened 2022-06-07</sub> -- :diamond_shape_with_a_dot_inside: <sub>(client-side changes only)</sub>

    - https://github.com/0x0ade/CelesteNet/pull/31
      <sub> - opened 2022-06-11</sub> -- :diamond_shape_with_a_dot_inside: <sub>(client-side changes only)</sub>

    - https://github.com/0x0ade/CelesteNet/pull/34
      <sub> - opened 2022-08-24</sub> -- :heart_decoration: <sub>(Server.FrontendModule only)</sub>

    - https://github.com/0x0ade/CelesteNet/pull/35
      <sub> - opened 2022-08-26</sub> -- :diamond_shape_with_a_dot_inside: <sub>(client-side changes only)</sub>

    - https://github.com/0x0ade/CelesteNet/pull/38
      <sub> - opened 2022-09-04</sub> -- :heart_decoration: <sub>(Server.FrontendModule only)</sub>

    - https://github.com/0x0ade/CelesteNet/pull/39
      <sub> - opened 2022-09-04</sub> -- :diamond_shape_with_a_dot_inside: <sub>(client-side changes only)</sub>

    - https://github.com/0x0ade/CelesteNet/pull/40
      <sub> - opened 2022-09-10</sub> -- :heart_decoration: <sub>(server-side changes only)</sub>

    - https://github.com/0x0ade/CelesteNet/pull/41
      <sub> - opened 2022-09-15</sub> -- :diamond_shape_with_a_dot_inside: <sub>(client-side changes only)</sub>

    - https://github.com/0x0ade/CelesteNet/pull/43
      <sub> - opened 2022-09-22</sub> -- :diamond_shape_with_a_dot_inside: <sub>(client-side changes only)</sub>

----

Messed around with Github API and git-log to find all commits that don't come from these merged branches?...

(Side note: Should we rebase before merges so that the commits don't get spliced into the existing history?)

The stuff I did, just for reference
```sh
for pull in 22 23 24 25 27; do 
     curl -s -H "Accept: application/vnd.github+json" -H "Authorization: token $PAT" "https://api.github.com/repos/0x0ade/CelesteNet/pulls/$pull/commits > pr_$pull.txt
done

for pull in 22 23 24 25 27; do
     commits="$(jq -r '.[]|.sha' < pr_$pull.txt)"
     echo "$commits"
done | tr -d '\r' > pr_commits.txt

git log --no-merges --since=2022-01-19 --oneline --no-abbrev-commit | grep -v -f pr_commits.txt
```

**non-merge commits**
```
2022-01-22 18:15:22     2d4bb16         Popax21         Clean up/Fix legacy code
2022-01-22 18:47:41     ea2913e         Popax21         Cleanup context core dispose
2022-01-22 18:58:47     d5be441         Popax21         Fix client disconnecting
2022-01-22 19:05:43     72742a7         Jade Macho      Cleanup
2022-01-22 19:18:16     62e3d7a         Jade Macho      Fix disconnect reason handler
2022-01-30 17:17:47     0328e1e         Popax21         Fix connection race condition
--- the above are probably already in server but not in client?...
2022-03-19 15:02:19     c55d6b3         Popax21         Improved connection disposal race condition handling
2022-07-03 01:05:06     9c1c404         Popax21         Fix UDP socket having incorrect address family
```

**Comment by RedFlames** [comment]
**TODO:** Update this comment.

I've been reviewing these again.

## Closed/merged PRs:
 -  [x] **Player list splitting (client-only changes)** 
   Been a while since I looked at all this myself but still looks fine to me and had been reviewed by jade already.
 -  [x] **ping**
   Looks fine to me if we merge https://github.com/0x0ade/CelesteNet/pull/28 on top of it.
 -  [x] **_2 merged client fixes_**
   Both look good to me too. 

Didn't actually look at the Control panel PR of mine again... not very relevant for public release and can be dealt with later.

## Open PRs:
 -  [ ] **Chat QoL: Tab completions - Server-side only**
   Still needs to be reviewed by others, but once we merge this, the other "Chat QoL" PR will be client-side only
 -  [x] **ping fixes**
    See merged ping PR above
 -  [x] **Ghost life cycle**
   Not sure I know enough about the Ghosts logic but looks like refactor + cleanup to me.
   :memo: Note: Has a `FIXME: NOTE BEFORE MERGING: ...` in the code, check the diff
 -  [x] **Misc render fixes**
   Three fixes that aren't related at all. The first one seems the most important to merge, because it causes those excessive calls to `Emoji.Fill`
 -  [x] **Interactions bug with the "Release me"**
   Kind of a critical fix, since the logic for when to `SendReleaseMe()` was very flawed.
 -  [x] **Control Panel chat log less cluttered**
   Would love to see this get merged as well, even if it's not the ideal solution to the existing problem.

## Open PRs for future releases:
 -  [ ] **Chat QoL improvements: Scrolling, Tab completions**
   TODO: Look at again. Update if we do merge #<sub></sub>33 first. Push back to later client update?
